version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onetappe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    restart: always
    env_file:
      - ../backend/.env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: